@startuml

skinparam backgroundColor transparent
skinparam monochrome reverse
...
note left of "Splunk Phantom"
Playbook Execution
end note
"Splunk Phantom" -> URLP: Generate Prompt
"Splunk Phantom" <- URLP: Prompt URL
"Splunk Phantom" -> Alice: Send Prompt URL
activate "Splunk Phantom"
loop until response
    "Splunk Phantom" <-> URLP: Poll Status
    Alice -> URLP: Prompt Response
    deactivate "Splunk Phantom"
end
...
@enduml